### ISSUE TITLE
EBSI Verifiable Authorization type does not match the expected by the VCTypeAdapter

### ISSUE THREAD

**Issue by xmartinez15** [walt-id/waltid-ssikit-vclib#29]
Verifiable Authorizations issued by EBSI Onboarding API have the type element "VerifiableAuthorisation" instead of "VerifiableAuthorization". This difference in the naming raises an error in the classFor function of this class:
https://github.com/walt-id/waltid-ssikit-vclib/blob/master/src/main/kotlin/id/walt/vclib/adapter/VCTypeAdapter.kt, as it doesn't recognize "VerifiableAuthorisation" as a valid type.

**Comment by severinstampler** [comment]
Please check, afair there are aliases defined for that case. So it should work anyway. Maybe the alias got lost with a recent update?

**Comment by xmartinez15** [comment]
I am using waltid-ssikit-vclib-1.7-SNAPSHOT, and when I use the function VerifiableCredential.fromString(string) with an EBSI generated V.Auth, this errror appears VcLib: "Unknown credential type: JsonArray(value=[VerifiableCredential, VerifiableAuthorisation])". If I modify the V.Auth and change "VerifiableAuthorisation" for "VerifiableAuthorization", the error disappears. Am I doing something wrong here?
