### ISSUE TITLE
Issues with Europass credential

### ISSUE THREAD

**Issue by ohylli** [walt-id/waltid-ssikit-vclib#39]
I have noticed multiple issues with the Europass credential where it does not
match the corresponding schema. For example
- learningOpportunityType, homePage, learningOutcome are missing from learning specification represented by class
  _Europass.EuropassSubject.Achieved.SpecifiedBy_
- Optional fields are marked as required for example startedAtTime for
  learning activity represented by
  _Europass.EuropassSubject.Achieved.WasInfluencedBy_
  
There have been others that have now been fixed. I wanted just to confirm that
we who work on this model are using the same source for it. So I use [this
schema](https://ec.europa.eu/cefdigital/code/projects/EBSI/repos/json-schema/browse/schemas/ebsi-muti-uni-pilot/verifiable-diploma/2021-11/schema.json) and [this non-public documentation](https://ec.europa.eu/cefdigital/wiki/pages/viewpage.action?spaceKey=EBSIEA&title=Verifiable+Diploma+Schema). I can make a pull request for
the learning outcomes and possible some other stuff that our use case requires.
I just wanted to make sure we are on the same page about this model.

**Comment by philpotisk** [comment]
Dear @ohylli, I took a look at the [EBSI Data Models & Schemas](https://ec.europa.eu/digital-building-blocks/wikis/display/EBSIEA/Data+Models+and+Schemas) which we are planning to support, and I would also conclude the same way as you did regarding the **Europass Credential**. 
- We should implement this schema: https://ec.europa.eu/digital-building-blocks/code/projects/EBSI/repos/json-schema/browse/schemas/ebsi-muti-uni-pilot/verifiable-diploma/2021-11/schema.json 
- and make sure that this example is working: https://ec.europa.eu/digital-building-blocks/code/projects/EBSI/repos/json-schema/browse/schemas/ebsi-muti-uni-pilot/verifiable-diploma/2021-11/examples/Ildiko%20Mazar_Graduate%20University%20Study%20of%20Civil%20Engineering_shortened.json
It would be fantastic if you would initiate a PR with the changes you are suggesting above. Thanks!

**Comment by atuffreau-bcd** [comment]
Indeed, the developments include support of the schema for specific examples that do not use all attributes for the schema. It is possible some of issues exist with unused attributes

**Comment by ohylli** [comment]
Just want to point out that I no means claim that my pull request #40 fixed all the issues with the model. Just those that I noticed in our particular use case so far.
