### ISSUE TITLE
Minimal Gaia-X Self-Description

### ISSUE THREAD

**Issue by philpotisk** [walt-id/waltid-ssikit-vclib#48]
The  Gaia-X Self-Description (Participant Credential) from https://gaia-x.atlassian.net/browse/LAB-109  or https://github.com/walt-id/waltid-ssikit-vclib/blob/master/src/test/resources/serialized/ParticipantCredential.json should be updated as follows:

Optional or remove:
- VC status
- ethereumAddress
- use DID as ID
- Date fields: "validFrom", "issuedDate" and "issued" as "created" is sufficient.

Proof:
- Add proofPurpose
- "proofValue" instead of "jws"
- value of verificationMethod -> resolvable X509 key from GAIA-X Registry

**Comment by kaimeinke** [comment]
Hi Phil, I agree that we need to include the DID as ID. This is part of the  DID Syntax in my opinion. https://www.w3.org/TR/did-core/#did-syntax

issuanceDate will be kept, same as expirationDate and created. There is no reason to remove expirationDate by now, although it is an optional field.

validFrom can be removed I would say.

The ethereumAddress can be kept, as it is optional.

The VC status need to be conform with the StatusList. I need to do a bit more research on this.

**Comment by kaimeinke** [comment]
We should include a StatusList according to https://w3c-ccg.github.io/vc-status-list-2021/ once we have a Revocation process in place. This might be a bit later, but is absolutely a good idea for the example credential. I think we can take care of this in a later change request.
